# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iWin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for iWin
  pod 'Google-Mobile-Ads-SDK'
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

#  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
#   pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  # pod 'react-native-fbsdk1', :path => '../node_modules/react-native-fbsdk'


#  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

#post_install do |installer|
#  fix_fb
#end
#
#def fix_fb
#  node_modules_path = '../node_modules'
#  patched_text = File.read("./RCTFBSDKLoginButtonManager.m.patch")
#  
#  File.open("../node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m", "w") {|file| file.puts patched_text}
#end
